name: CD:- Cloudformation

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.LEO_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.LEO_AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.LEO_AWS_ACCOUNT_ID }}
      AWS_REGION: us-west-2
      NOTIFICATIONS_TABLE: ''
      ENVIRONMENT_NAME: 'dev'
      RELEASE_VERSION: '1.0.0'
      SENTRY_DSN: 'https://f4ff9b31e2d040efb15e1b673c8418f3@o4504317618487296.ingest.sentry.io/4504598531342336'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install serverless dependency
        run: yarn install --frozen-lockfile
      - name: Package Functions
        run: npx serverless package
      - name: Deploy Functions - dev account
        run: npx serverless deploy --package .serverless
